name: task_hotel
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #infrastructure
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  freezed: ^2.1.0+1
  built_value: ^8.1.2
  provider: ^6.0.1
  dartz: ^0.10.0
  chopper: ^6.1.4
  path_provider: ^2.0.10
  permission_handler: ^10.0.0
  logger: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  image: ^4.0.17
  path: ^1.8.1
  built_collection: ^5.1.1
  freezed_annotation: ^2.1.0
  mask_text_input_formatter: ^2.3.0
  pdf: ^3.8.4
  open_filex: ^4.3.2
  document_file_save_plus: ^2.0.0
  file: ^6.1.4
  webview_flutter: ^4.2.0
  webview_flutter_wkwebview: ^3.4.0
  webview_flutter_android: ^3.6.2
  alice: ^0.3.2


  #ui
  flutter_screenutil: ^5.8.4
  easy_localization: ^3.0.0
  #  image_cropper: ^2.0.3
  progress_indicators: ^1.0.0
  animate_do: ^3.0.2
  flutter_easyloading: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4
  pinput: ^3.0.0
  table_calendar: ^3.0.6
  intl_phone_number_input: ^0.7.0+2
  wechat_camera_picker: ^4.0.0
  wechat_assets_picker: ^8.6.3
  intl: ^0.18.0
  dotted_line: ^3.1.0
  pull_to_refresh: ^2.0.0
  package_info_plus: any
  badges: ^3.1.0
  persistent_bottom_nav_bar: ^5.0.2
  fluttertoast: ^8.1.2
  logging: ^1.1.0
  url_launcher: ^6.1.12
  flutter_localization: ^0.1.9
  sms_autofill: ^2.3.0
  flutter_local_notifications: ^14.1.2
  #  image_cropper: ^3.0.2
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  libphonenumber_plugin: ^0.3.2
  device_preview: ^1.1.0
  flutter_layout_grid: ^2.0.1
  shimmer: ^3.0.0
  flutter_multi_formatter: ^2.10.3
  easy_refresh: ^3.3.1
  location: ^5.0.3
  flutter_timezone: ^1.0.4
  timezone: ^0.9.1
  extended_masked_text: ^2.3.1
  html: ^0.15.4
  google_fonts: ^5.1.0

  #  firebase
#  firebase_core: ^2.7.0
#  firebase_dynamic_links: ^5.0.15
#  firebase_messaging: ^14.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  chopper_generator: ^6.0.3
  built_value_generator: ^8.1.2
  flutter_launcher_icons: ^0.13.1

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  remove_alpha_ios: true
#  image_path: "assets/images/launch_logo.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21
#  web:
#    generate: true
#    image_path: "assets/images/launch_logo.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"
#  windows:
#    generate: true
#    image_path: "assets/images/launch_logo.png"
#    icon_size: 48 # min:48, max:256, default: 48
#  macos:
#    generate: true
#    image_path: "assets/images/launch_logo.png"

flutter:

  uses-material-design: true



  assets:
    - assets/
    - assets/translation/
    - assets/images/
    - assets/icons/svg/

